# Generated by Django 6.0.3 on 2026-04-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="blog_post_photos/")),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-posted_date"],
            },
        ),
    ]
