# Generated by Django 6.0.3 on 2026-04-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_blogpost_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="owner",
            new_name="author",
        ),
    ]
