# Generated by Django 6.0.3 on 2026-03-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contacts_alter_product_category_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name_plural": "Контакты"},
        ),
    ]
