# Generated by Django 6.0.3 on 2026-03-26 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_contacts_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"ordering": ["-created_date"], "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="contacts",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
